# vi:syntax=dockerfile
FROM openquake/engine
MAINTAINER Daniele Viganò <daniele@openquake.org>

ADD scripts/celery-wait.sh ${HOME}
ADD conf/openquake.cfg /etc/openquake

ENTRYPOINT ["/opt/openquake/bin/python3", "-m", "celery"]
CMD ["worker", "--config", "openquake.engine.celeryconfig", "--purge", "-O", "fair"]
